Repository kserve/website, pull requests merged in 2022-10, with the labels that each got.

#190 Add grpc example for lightgbm
  docs/modelserving/v1beta1/lightgbm/README.md
  docs/modelserving/v1beta1/lightgbm/iris-input-v2-grpc.json
  docs/modelserving/v1beta1/lightgbm/lightgbm-v2-grpc.yaml
  docs/modelserving/v1beta1/triton/torchscript/README.md
Labels: approved

#192 Consolidate CIFAR-10 Outlier Notebook Sample
  docs/modelserving/detect/alibi_detect/alibi_detect.md
  docs/modelserving/detect/alibi_detect/cifar10_outlier.ipynb
Labels: lgtm, approved

#197 Update inference graph docs
  docs/modelserving/inference_graph/README.md
Labels: lgtm, approved

#196 add directions for making PR / issue
  docs/developer/developer.md
Labels: lgtm, approved, hacktoberfest, hacktoberfest-accepted

#176 Add Xin, Alexa, Sukumar to reviewer
  OWNERS
Labels: lgtm, approved

#198 Add code generate instruction on developer guide
  docs/developer/developer.md
Labels: lgtm, approved
