Repository kserve/website, pull requests merged in 2023-03, with the labels that each got.

#232 'Example output' boxes + wrap cURL call in quotes
  docs/get_started/first_isvc.md
Labels: lgtm, approved

#235 Fix continuous redirect
  404.html
Labels: lgtm

#233 Update adopters with Canonical's
  docs/community/adopters.md
Labels: lgtm, approved

#237 Change Striveworks contact
  docs/community/adopters.md
Labels: lgtm, approved

#238 Fix Knative min requirement
  docs/admin/serverless/serverless.md
Labels: approved
