Repository kserve/website, pull requests merged in 2023-10, with the labels that each got.

#292 Update README.md to add intermediate installation steps
  docs/get_started/README.md
Labels: lgtm, approved

#299 Fixes raw deployment ingress class version
  docs/admin/kubernetes_deployment.md
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#301 added step in readme to install requirements.txt
  docs/help/contributor/mkdocs-contributor-guide.md
Labels: lgtm, approved, hacktoberfest-accepted

#300 Fixes #244 to point the kserve repo, not website repo
  mkdocs.yml
Labels: lgtm, approved, hacktoberfest-accepted

#273 Add open inference protocol support docs and runtime priority docs
  docs/modelserving/servingruntimes.md
  docs/modelserving/v1beta1/lightgbm/README.md
  docs/modelserving/v1beta1/sklearn/v2/README.md
  docs/modelserving/v1beta1/xgboost/README.md
Labels: lgtm, approved

#294 Add storage container docs
  docs/modelserving/storage/storagecontainers.md
  mkdocs.yml
Labels: lgtm, approved

#306 Add grpc docs and missing OIP docs for some runtimes
  docs/developer/developer.md
  docs/modelserving/v1beta1/lightgbm/README.md
  docs/modelserving/v1beta1/lightgbm/iris-input-v2-grpc.json
  docs/modelserving/v1beta1/lightgbm/lightgbm-v2-grpc.yaml
  docs/modelserving/v1beta1/paddle/README.md
  docs/modelserving/v1beta1/paddle/jay-v2-grpc.json
  docs/modelserving/v1beta1/paddle/jay-v2.json
  docs/modelserving/v1beta1/pmml/README.md
  docs/modelserving/v1beta1/sklearn/v2/README.md
  docs/modelserving/v1beta1/spark/README.md
  docs/modelserving/v1beta1/torchserve/model-archiver/README.md
  docs/modelserving/v1beta1/xgboost/README.md
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#304 Add TorchServe Huggingface accelerate example
  docs/modelserving/v1beta1/llm/torchserve/accelerate/README.md
  docs/modelserving/v1beta1/llm/torchserve/accelerate/bloom.yaml
  docs/modelserving/v1beta1/llm/torchserve/accelerate/config.properties
  docs/modelserving/v1beta1/llm/torchserve/accelerate/custom_handler.py
  docs/modelserving/v1beta1/llm/torchserve/accelerate/setup_config.json
  docs/modelserving/v1beta1/llm/torchserve/accelerate/text.json
  mkdocs.yml
Labels: approved
